### ISSUE TITLE
Add in payment type

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/payments-config#10]
eg: subscription, monthly vs one-off

**Comment by andymckay-limited-access** [comment]
Tracking mozilla/payments#82

**Comment by andymckay** [comment]
Tracking mozilla/payments#117

**Comment by kumar303** [comment]
We also need to know whether or not the payment can be "anonymous" (i.e. for donations) so that we can choose to sign in the user or not. This should probably be a separate type because donations could be one-off _or_ recurring.

**Comment by andymckay** [comment]
Sounds good
