### ISSUE TITLE
map payment method IDs to names (e.g. credit cards)

### ISSUE THREAD

**Issue by kumar303** [mozilla/payments-config#6]
In payments service we need to send receipt emails (https://github.com/mozilla/payments-service/issues/58). Part of that is showing 'Paid with: Visa ending in xxxx' so we need to map paymethod type IDs to credit card names. Seems like a good time to move this into the payments-config since the UI already has a mapping for this.

**Comment by andymckay-limited-access** [comment]
Thats type and type_name in the pay method response:

```
mysql> select type, type_name from braintree_pay_method;
+------+-----------+
| type | type_name |
+------+-----------+
|    1 | Visa      |
+------+-----------+
1 row in set (0.00 sec)
```

Type is credit card/carrier billing/bitcoin/other. Use type_name and you should be good.

I think based on this, there's nothing to do here.

**Comment by kumar303** [comment]
oh cool! I missed that
